GET http://localhost:3000/health

###
POST http://localhost:3000/calculate/yield
Content-Type: application/json

{
    "annualDividendPerShare": 5.00,
    "sharePrice": 300.00
}

###
POST http://localhost:3000/calculate/payout
Content-Type: application/json

{
    "dividendPerShare": 5.00,
    "earningsPerShare": 20.00
}

###
POST http://localhost:3000/calculate/drip
Content-Type: application/json

{
    "initialInvestment": 1000,
    "annualDividendYield": 4,
    "years": 10,
    "frequency": 12,
    "annualDividendGrowth": 2,
    "annualShareGrowth": 3,
    "monthlyContribution": 100
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "login": "usuario1",
    "password": "1234"
}